### ISSUE TITLE
Shortcut request for Align button

### ISSUE THREAD

**Issue by Orama7** [Red5goahead/VisualSubSync-Enhanced#10]
Hello,

Greetings from the greek subtitlers community!

We are using the Quick & Smart Delay to resync our subtitles and we find it very useful.

A keyboard shortcut for the main button (Align) would speed up the process of resyncing considerably.

Will you consider this for a future release?

Thank you very much, and have a nice day!

**Comment by Red5goahead** [comment]
Hi

Please, post me an image to explain better. Do you mean a shortcut for 'Insert a new desynch..'?

**Comment by Orama7** [comment]
No, I mean the big button inside the [Quick & Smart Delay] panel.

See image, the button's border is painted red:
https://i.imgur.com/XKGNhCT.png

**Comment by Red5goahead** [comment]
You can set a custom hot key

http://imgur.com/iqKTplu

**Comment by Orama7** [comment]
After using it for a while, I must say:

That's exactly what we need!

Thanks!
