### ISSUE TITLE
Request: SBV format support

### ISSUE THREAD

**Issue by StareInTheAir** [Red5goahead/VisualSubSync-Enhanced#15]
It would be nice to be able to load and save subtitles in the SBV format. Here is a comparison between the SRT and SBV format.

SRT:
```
160
00:08:09,610 --> 00:08:12,480
I who you are, and I think
you would do the right thing.

161
00:08:12,481 --> 00:08:15,990
I think you wouldn’t jerk people around.
I think you’d be there to serve.

162
00:08:15,991 --> 00:08:18,215
But it also depends on your haircut.
```

SBV:
```
0:08:09.610,0:08:12.480
I who you are, and I think
you would do the right thing.

0:08:12.481,0:08:15.990
I think you wouldn’t jerk people around.
I think you’d be there to serve.

0:08:15.991,0:08:18.215
But it also depends on your haircut.
```

SRT and SBV are quite similar. SBV is used by YouTube and would also be quite useful if one would version SBV files with Git to collaborate on creating subtitles. The missing id number would make resolving conflicts much easier.

SBV to SRT converter websites exist, but built-in support would be very nice to have:

- https://www.dcmp.org/ciy/converting-youtube-to-srt.html
- http://captionsconverter.com/

**Comment by Red5goahead** [comment]
Hi

There is a long-term project to add import/export from and to any knows formats including Netflix

**Comment by Red5goahead** [comment]
soon
