### ISSUE TITLE
VisualSubSync does not generate the full peak file

### ISSUE THREAD

**Issue by Alexisback** [Red5goahead/VisualSubSync-Enhanced#17]
versione 1.2.23.01

The peak file for audio is generated cut (00: 02: 26.919) about 2 minutes and a half
Film length 4 h 11 min

Where am I wrong?

![screen capture 083](https://user-images.githubusercontent.com/18039740/27708458-b2be71e2-5d21-11e7-85f6-af33acc9e5bb.png)

![screen capture 084](https://user-images.githubusercontent.com/18039740/27708459-b2c2c7a6-5d21-11e7-9b70-d607132b7a0e.png)

**Comment by Alexisback** [comment]
nessuno mi aiuta?

**Comment by nixxo** [comment]
try extracting with the alternative method:
![27708458-b2be71e2-5d21-11e7-85f6-af33acc9e5bb](https://user-images.githubusercontent.com/426049/27828066-98297d3a-60ba-11e7-83fb-fc46f62d16f2.png)

**Comment by Alexisback** [comment]
Hi nixxo

Even this method does not work
extracts only 2 minutes and 30

**Comment by nixxo** [comment]
have you tried extracting a different audio track in the dropdown menù...

**Comment by Alexisback** [comment]
Yes, I extracted the different audio
does not work
This is the first time this happens
I synced many TV series and movies
This video is hard, maybe depends on the duration, more than 4 hours

**Comment by nixxo** [comment]
can you link the video... if it's not too big i'll try to download it.

**Comment by Alexisback** [comment]
Hi nixxo
Sorry for late reply
The video is big enough, 17,66 GBytes
Once Upon a Time in America (Extended Cut) 1984
language Russian and English

I want to sync the Italian subtitles with the English track

**Comment by Alexisback** [comment]
Tried with another video (a tv series) and the peak is normally extracted
Episode duration 59 min

I suspect that over 4 hours can not extract the peak

**Comment by Red5goahead** [comment]
Try to remux the file and use the remuxed file with audio file / remux operation
