### ISSUE TITLE
Request: Urban Dictionary

### ISSUE THREAD

**Issue by jimmy213** [Red5goahead/VisualSubSync-Enhanced#19]
Could you add https://www.urbandictionary.com/ in the "Online dictionary search"?

Thanks.

**Comment by Red5goahead** [comment]
Why should I ever prefer to use urbandictionary over wordnet?

**Comment by jimmy213** [comment]
They are two different (mostly) things. Urbandictionary contains English slang and it might be useful in some translations.
Wordnet is a very good English to English dictionary and it's very nice that you included it in VSS. I didn't say to remove it.
I just proposed an extra dictionary option, not removal of the existing ones.

**Comment by Red5goahead** [comment]
Ok, reasonable. My only doubt is about advertising that cannot be deleted in the internal browser

**Comment by Red5goahead** [comment]
I've to work on their Api that return info as Json format

ex.
http://api.urbandictionary.com/v0/define?term=school

**Comment by MintHawk** [comment]
Thank you for your time and effort.
