### ISSUE TITLE
[Solved] System Error Code 2 when converting to dfxp format

### ISSUE THREAD

**Issue by nicissimo97** [Red5goahead/VisualSubSync-Enhanced#25]
Hi red, i keep getting the error below when attempting to convert .srt to .dfxp, .sbv or .vtt
running v. 1.2.26.00 desktop version
![cattura](https://user-images.githubusercontent.com/6663349/33242893-e229eca6-d2db-11e7-803c-d64deabff0f8.PNG)

**Comment by Red5goahead** [comment]
The installer has been updated and now should work fine
