### ISSUE TITLE
Missing/bad scene change

### ISSUE THREAD

**Issue by ianonthenet** [Red5goahead/VisualSubSync-Enhanced#26]
Hi!
I noticed that I often have problems with scene changes detection.
Some times, (obvious) scene change are not detected, and some times, a scene change appears when there is absolutely no movement in the video.
Someone has a idea on this problem ?
Thanks
![sc](https://user-images.githubusercontent.com/12033474/35749753-e260b234-0852-11e8-82ef-aae0c3dc596a.png)

**Comment by nixxo** [comment]
the new version has precise scene-change extraction. try it.
