### ISSUE TITLE
Column order

### ISSUE THREAD

**Issue by nixxo** [Red5goahead/VisualSubSync-Enhanced#27]
The column order is saved to the configuation file in the wrong order.

**Comment by Red5goahead** [comment]
Nixxo prova con la v. 1.2.27 . l'ultima. Secondo me ora funziona. Non riesco a replicarla

**Comment by nixxo** [comment]
il problema c'è ancora.

Installo Delphi visto che ho il PC pulito e provo a dare un'occhiata.

**Comment by Red5goahead** [comment]
Va bene. oppure registra un video con il percorso che porta all'errore. credo di non avere fatto le prove nel modo corretto.

**Comment by nixxo** [comment]
sposta le colonne a caso, esci da vss e quando rientri non sempre le colonne sono ordinate come le hai lasciate chiudendo vss. L'ordinamento viene salvato (o ripristinato all'avvio) in maniera non corretta.


off topic: anche perchè installando delphi mi da un casino di problemi che non trova librerie varie ecc. e sto provando a reinstallarlo.
