### ISSUE TITLE
"Audio waveform/peak file" selection isn't working

### ISSUE THREAD

**Issue by jimmy213** [Red5goahead/VisualSubSync-Enhanced#39]
If a file (usually .mkv) contains two (or more) audio streams, I can't select whichever I want in the "Audio waveform" section.

For example, I want the Spanish audio.

![screenshot_10](https://user-images.githubusercontent.com/29613978/47736260-005b4300-dc77-11e8-846f-0a46bb3fff50.png)

If I choose it and create the project, VSS extracts the English audio and not what I selected. I think it messes with the "Preferred languages" in Preferences|Playback.

In my opinion, "Preferred languages" box doesn't make much sense. We should be able to select the audio stream when we create a new project.

**Comment by nixxo** [comment]
After you selected the audio track, do you hit "Start selected operation..." or "Extract wave..."?

**Comment by jimmy213** [comment]
Maybe I'm a little silly. I just hit the "Create new project" at the bottom, but maybe that's wrong.
I should hit "Start selected operation..." to extract the stream I want?

**Comment by nixxo** [comment]
Yup.

**Comment by jimmy213** [comment]
I just tried that and it still gives me the English audio.

**Comment by nixxo** [comment]
ok, there is a problem in the extraction process.

But it should extract the "first" audio track, so the spanish one should be extracted. Can you provide the fille for some tests?

**Comment by jimmy213** [comment]
Sure. Here's the file
https://goo.gl/qzMHtN

**Comment by Red5goahead** [comment]
fixed in the next release

**Comment by jimmy213** [comment]
Thank you :)
