### ISSUE TITLE
VMware e VMR9

### ISSUE THREAD

**Issue by Superpiffer** [Red5goahead/VisualSubSync-Enhanced#40]
Ho aggiornato VSS all'ultima versione sulla mia VM con Windows 10 e mi sono accorto che il video non funziona più, ho solo l'audio. Per qualche motivo con le versioni precedenti ho il video solo con il VMR7, sarebbe possibile dare di nuovo la possibilità di utilizzarlo? Ovviamente lasciando VMR9 come default.
Grazie.

EDIT: il motivo è l'accelerazione 3D, quando è disattivata VMR9 non riproduce i video. Per retrocompatibilità magari sarebbe utile lasciare anche la vecchia versione.

**Comment by Red5goahead** [comment]
Il problema è che con Vmr7 ci sono dei problemi con Windows 10. L'ho tolto per questo. Rimetterlo non sarebbe un problema. L'ideale sarebbe utilizzare il renderer evr ma per qualche motivo che non ho mai capito non ha mai funzionato nemmeno con Windows 7
