### ISSUE TITLE
Wrong extraction of subtitle file

### ISSUE THREAD

**Issue by MintHawk** [Red5goahead/VisualSubSync-Enhanced#41]
Hello, everyone, and thank you for your great work.
I tried extracting the english .srt from a video file but it extracted the french one.
It does that every time I ask the program to extract any .srt (including other language .srt files, e.g. German or Spanish), Of course, I don't know if it's a video file thing but can someone check this out?
When I tried extracting the only .srt from another video file (english one), it extracted it successfully.

I'm using 1.2.27.00.

Many thanks in advance.

**Comment by nixxo** [comment]
can you provide the video filename?

**Comment by MintHawk** [comment]
I think it was this one: The.Last.Kingdom.S03E03.PROPER.720p.WEB.x264-STRiFE
It can be found here: [link removed]

Edit: removed link

**Comment by MintHawk** [comment]
Many thanks, guys, for the prompt solution.
Subtitle extraction works like a charm in release 1.2.30.0.
