### ISSUE TITLE
New Project window not compatible with 125% display setting

### ISSUE THREAD

**Issue by hivolbill** [Red5goahead/VisualSubSync-Enhanced#52]
I have so few issues with having my display set on 125% that I forgot it was set that way, so it took me a while to get around the New Project window being below my monitor line and me unable to push the create project button.  The New Project window was not adjustable.

I fully accept that the issue might be my settings and not the program, but I wanted to call it to someone's attention.

**Comment by nixxo** [comment]
ok, saw the issue. I'll try to fix it.
