### ISSUE TITLE
Waveform and video stop for a second when hitting play button.

### ISSUE THREAD

**Issue by Marcel107** [Red5goahead/VisualSubSync-Enhanced#57]
Hello. When i open a new project and i hit the play to end button the video and the waveform get stuck for a sec and then continue faster. Also sometimes when i hit the play to end the waveform and the video jump some seconds and start going from there. This happens to me with all versions of VSS.

**Comment by gru123** [comment]
I am on Windows 10-x64. I had the same problem with VisualSubSync v1.0.2016.1204 (spirit's custom build), but I switched to VisualSubSync-Enhanced v1.2.31.00 and the problem gone. I guess it's codec related.
BTW there was no such problem on Windows 7.
Make sure your GPU drivers are up to date, and uninstall unnecessary codec packs (eg K-Lite). Check "Playback" settings in VSS and "internal LAV Video Decoder" settings (the green arrow icon in system tray when project is open in VSS):
![1Preferences](https://user-images.githubusercontent.com/42896067/99640699-8d81b800-2a49-11eb-97b4-07ca4c9ed7ea.png)
![2LAV Video Decoder (internal)](https://user-images.githubusercontent.com/42896067/99640704-8eb2e500-2a49-11eb-88f6-48accb98eb22.png)
Please specify your OS, GPU type and VSS version, it will help to diagnose the problem.

**Comment by Red5goahead** [comment]
glad to hear. I should be able to keep at least the new codecs up to date
