### ISSUE TITLE
[Suggestion] Moving to Lazarus

### ISSUE THREAD

**Issue by jimmy213** [Red5goahead/VisualSubSync-Enhanced#59]
Is there any chance of moving the project to Lazarus instead of Delphi?

That could help making the program cross-platform. Linux and MacOS users don't have any subtitle program as good as this one (at least I'm not aware of any).

I tried to mess around a little converting the source files, but I don't have any experience with Pascal.

**Comment by Red5goahead** [comment]
Hi, no I don't think that's possible. The project was very much linked to Italiansubs, which however closed its main subtitling activity. Recently it started again with TV series but there are no ongoing activities involving VisualSubSync-Enhanced. About a year ago I still made some changes and updated the codecs in the installation and I can maybe grant some bug fixes yet but not substantial implementations
