### ISSUE TITLE
portable version

### ISSUE THREAD

**Issue by Alexisback** [Red5goahead/VisualSubSync-Enhanced#9]
hello to the whole team
thanks for your work
question:
possible to create a portable version of "VisualSubSync" with the settings saved in the same folder as the program?

it would be useful

**Comment by Red5goahead** [comment]
Hi

It should be possible but there were a lots of improvments since base Visualsubsync was released especially for the security issues and the configuration that must be located in the AppData folder of the logged user. Also with the Microsoft Store release. There was a portable version some years ago but now is deprecated. I'll try to update it

bye

**Comment by Alexisback** [comment]
it would be very useful,
I use it on other computers, and do not want to install and configure it every time
thank you

**Comment by Alexisback** [comment]
news for portable version ?

**Comment by Red5goahead** [comment]
Not yet. I had to work for an issue with Greek users

**Comment by Red5goahead** [comment]
Download the portable version from release area and try it

https://github.com/Red5goahead/VisualSubSync-Enhanced/releases

**Comment by Alexisback** [comment]
thank you so much

**Comment by Alexisback** [comment]
It's not the portable version 
When I start the program, a folder is created in "**C:\Users\utente\AppData\Roaming\VisualSubSyncEnh**"
With these files
**perso.dic
VisualSubSync.ini**
In these and saving the configuration,
But if they are not saved in the portable folder where the program will lose all settings

**Comment by Alexisback** [comment]
I have an earlier version that works fine in the portable version (1.0.2.12), configuration is created and saved in the same folder of the program

**Comment by Red5goahead** [comment]
Try again with the new zip file. If INI and perso.dic are on the portable folder, these files are used.
But the new version avoid to create the folder in the user data path

**Comment by Alexisback** [comment]
I reloaded the portable version and now the 2 files e folder are not recreated in the "User"

Tomorrow I try to see if everything is ok

thank you  Red5goahead 

Ps: Are you Italian?

**Comment by Red5goahead** [comment]
Yes I am

**Comment by Alexisback** [comment]
Ok, allora posso ringraziarti nella nostra lingua , sono anche io italiano (ma vivo all'estero),
sono iscritto al forum di italiansub, ho scoperto questo fantastico software li.
Grazie al team per quello che fate.

**Comment by Red5goahead** [comment]
Bene. grazie
